syntax = "proto3";

package medusa.flow.control_service.v1;

option java_multiple_files = true;
option java_package = "software.medusa.grpc.flow.control_service.v1";

service GrpcControlService {
  rpc ListFlows(GrpcControlServiceListFlowsRequest) returns (GrpcControlServiceListFlowsResponse);
  rpc CreateFlow(GrpcControlServiceCreateFlowRequest) returns (GrpcControlServiceCreateFlowResponse);
  rpc UpdateFlow(GrpcControlServiceUpdateFlowRequest) returns (GrpcControlServiceUpdateFlowResponse);
  rpc CheckTaskGraph(GrpcControlServiceCheckTaskGraphRequest) returns (GrpcControlServiceCheckTaskGraphResponse);
  rpc StartFlow(GrpcControlServiceStartFlowRequest) returns (GrpcControlServiceStartFlowResponse);
  rpc GetRunningFlowProgress(GrpcControlServiceGetRunningFlowProgressRequest) returns (GrpcControlServiceGetRunningFlowProgressResponse);
}

message GrpcControlServiceListFlowsRequest {}

message GrpcControlServiceListFlowsResponse {
  repeated PbFlowDump flows = 1;
}

message GrpcControlServiceCreateFlowRequest {
  PbFlowDetails details = 3;
}

message GrpcControlServiceCreateFlowResponse {
  string flow_id = 1;
}

message PbFlowState {
  oneof state {
    PbFlowDraftState draft = 1;
    PbFlowRunningState running = 2;
  }
}

message PbFlowDraftState {}

message PbFlowRunningState {}

message PbFlowDump {
  string id = 1;
  PbFlowState state = 2;
  PbFlowDetails details = 3;
}

message PbFlowDetails {
  string title = 2;
  PbTaskGraph task_graph = 4;
}

message GrpcControlServiceUpdateFlowRequest {
  string flow_id = 1;
  PbFlowDetails details = 2;
}

message GrpcControlServiceUpdateFlowResponse {}

message PbTaskGraphValidationFailedStatus {}

message GrpcControlServiceCheckTaskGraphRequest {
  PbTaskGraph task_graph = 1;
}

message GrpcControlServiceCheckTaskGraphResponse {
  oneof result {
    PbTaskGraphValidResult valid = 1;
    PbTaskGraphValidationFailedStatus validation_failed = 2;
  }
}

message PbTaskGraphValidResult {}

message GrpcControlServiceStartFlowRequest {
  string flow_id = 1;
  PbFlowDetails final_details = 2;
}

message GrpcControlServiceStartFlowResponse {
  oneof result {
    PbFlowStartedResult started = 1;
    PbTaskGraphValidationFailedStatus validation_failed = 2;
  }
}

message GrpcControlServiceGetRunningFlowProgressRequest {
  string flow_id = 1;
}

message GrpcControlServiceGetRunningFlowProgressResponse {
  PbRunningFlowProgress running_flow_progress = 1;
}

message PbFlowStartedResult {
  PbFlowDetails started_flow_details = 2;
}

message PbRunningFlowProgress {
  repeated PbTaskExecutionProgress task_execution_progresses = 1;
}

message PbTaskExecutionProgress {
  string task_id = 1;
  double progress = 2;
}

message PbTaskGraph {
  repeated PbTask tasks = 1;
}

message PbTask {
  string id = 1;
  repeated string source_task_ids = 4;
  double progress = 7;
  double x = 5;
  double y = 6;

  oneof kind {
    PbFeatureTask feature_task = 2;
    PbMergeTask merge_task = 3;
  }
}

message PbFeatureTask {
  string label = 1;
  string description = 2;
}

message PbMergeTask {}
