[versions]
armeria = "1.38.0"
detekt = "1.23.8"
grpc = "1.80.0"
grpc-kotlin = "1.5.0"
kotlin = "2.3.21"
kotlin-coroutines = "1.10.2"
ktfmt = "0.26.0"
logback = "1.5.32"
protobuf = "4.34.1"
protobuf-plugin = "0.10.0"
versionCatalogUpdate = "1.1.0"

[libraries]
armeria-bom = { module = "com.linecorp.armeria:armeria-bom", version.ref = "armeria" }
armeria-grpc = { module = "com.linecorp.armeria:armeria-grpc", version.ref = "armeria" }
armeria-grpc-kotlin = { module = "com.linecorp.armeria:armeria-grpc-kotlin", version.ref = "armeria" }
armeria-kotlin = { module = "com.linecorp.armeria:armeria-kotlin", version.ref = "armeria" }
grpc-bom = { module = "io.grpc:grpc-bom", version.ref = "grpc" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-protocGen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
protobuf-protocGen-grpc-kotlin = "io.grpc:protoc-gen-grpc-kotlin:1.5.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
