version: "3"

includes:
  github:
    taskfile: .github/Taskfile.yml
    dir: github

  cli:
    taskfile: cli/Taskfile.yml
    dir: cli

  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

  web:app:
    taskfile: web-app/Taskfile.yml
    dir: web-app

  web:infra:
    taskfile: web-app/infra/foundation/Taskfile.yml
    dir: web-app/infra/foundation

  web:domain-mapping:
    taskfile: web-app/infra/domain-mapping/Taskfile.yml
    dir: web-app/infra/domain-mapping

  api:impl:
    taskfile: backend/api/Taskfile.yml
    dir: backend/api

  api:infra:
    taskfile: backend/infra/Taskfile.yml
    dir: backend/infra

# noinspection YAMLSchemaValidation
.kotlinSources: &kotlinSources
  - '**/*.kt'
  - '**/*.kts'

tasks:
  all:checkFormatting:
    desc: Check formatting for the entire codebase
    deps:
      - github:workflows:lint
      - github:config:lint
      - infra:lint
      - web:app:checkFormatting
      - web:infra:checkFormatting
      - web:domain-mapping:checkFormatting
      - gradleRoot:checkFormatting
      - api:infra:checkFormatting

  all:fixFormatting:
    desc: Fix formatting for the entire codebase
    deps:
      - github:workflows:fixLint
      - github:config:fixFormatting
      - infra:fixFormatting
      - web:app:fixFormatting
      - web:infra:fixFormatting
      - web:domain-mapping:fixFormatting
      - api:infra:fixFormatting
      - gradleRoot:fixFormatting

  all:lint:
    desc: Lint the entire codebase
    deps:
      - github:workflows:lint
      - github:config:lint
      - infra:lint
      - web:app:lint
      - web:infra:lint
      - web:domain-mapping:lint
      - api:infra:lint
      - gradleRoot:analyzeStatically

  all:analyze:
    desc: Analyze the entire codebase
    deps:
      - github:config:validate
      - infra:validate
      - web:app:analyze
      - web:infra:validate
      - web:domain-mapping:validate
      - api:infra:validate

  gradleRoot:checkFormatting:
    desc: Check Kotlin formatting
    sources: *kotlinSources
    cmds:
      - ./gradlew ktfmtCheck
    interactive: true

  gradleRoot:fixFormatting:
    desc: Fix Kotlin formatting
    sources: *kotlinSources
    cmds:
      - ./gradlew ktfmtFormat
    interactive: true

  gradleRoot:compile:
    desc: Compile the Kotlin sources
    sources: *kotlinSources
    cmds:
      - ./gradlew compileKotlin
    interactive: true

  gradleRoot:analyzeStatically:
    desc: Lint the Kotlin sources
    sources: *kotlinSources
    cmds:
      - ./gradlew assemble
      - ./gradlew detekt
    interactive: true

  run:
    desc: Run the frontend and the API locally
    deps:
      - web:app:run
      - api:impl:run
