version: "3"

includes:
  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

  console-web:code:
    taskfile: apps/console-web/code/frontend/Taskfile.yml
    dir: apps/console-web/code/frontend

# noinspection YAMLSchemaValidation
.workflowSources: &workflowSources
  - ".github/workflows/*.yml"
  - ".github/actions/*/action.yml"

tasks:
  github-ci:lint:
    desc: Lint GitHub workflows
    sources: *workflowSources
    cmds:
      - github-ci lint

  github-ci:fixLint:
    desc: Fix lint issues in GitHub workflows
    sources: *workflowSources
    cmds:
      - github-ci lint --fix

  github-ci:upgrade:
    desc: Upgrade GitHub workflow actions to the latest versions
    cmds:
      - github-ci upgrade

  all:checkFormatting:
    desc: Check formatting for the entire codebase
    deps:
      - github-ci:lint
      - infra:checkFormatting
      - console-web:code:checkFormatting

  all:fixFormatting:
    desc: Fix formatting for the entire codebase
    deps:
      - github-ci:fixLint
      - infra:fixFormatting
      - console-web:code:fixFormatting

  all:lint:
    desc: Lint the entire codebase
    deps:
      - github-ci:lint
      - infra:lint
      - console-web:code:lint

  all:analyze:
    desc: Analyze the entire codebase
    deps:
      - console-web:code:typecheck
