package software.medusa.flow.harness.history

import kotlinx.serialization.Serializable

/**
 * A stored chunk summary — Markdown targeting the *leader's* needs (what a planner with less
 * context must not lose). Generated by an extra request into the just-finished assistant thread at
 * chunk close (story 07); this milestone only stores and renders them.
 */
@Serializable
@JvmInline
value class HrsChunkSummary(
    val markdown: String,
)
