syntax = "proto3";

package medusa.flow.core_service.v1;

option java_multiple_files = true;
option java_package = "software.medusa.grpc.flow.core_service.v1";

service CoreService {
  rpc ListSessions(ListSessionsRequest) returns (ListSessionsResponse);
  rpc UpdateSession(UpdateSessionRequest) returns (UpdateSessionResponse);
  rpc CheckTaskGraph(CheckTaskGraphRequest) returns (CheckTaskGraphResponse);
  rpc StartSession(StartSessionRequest) returns (StartSessionResponse);
}

message ListSessionsRequest {}

message ListSessionsResponse {
  repeated SessionSummary sessions = 1;
}

message SessionSummary {
  string session_id = 1;
  string title = 2;
  TaskGraph task_graph = 3;
}

message UpdateSessionRequest {
  string session_id = 1;
  string title = 2;
  TaskGraph task_graph = 3;
}

message UpdateSessionResponse {}

message TaskGraphValidationFailedStatus {}

message CheckTaskGraphRequest {
  TaskGraph task_graph = 1;
}

message CheckTaskGraphResponse {
  oneof result {
    TaskGraphValidResult valid = 1;
    TaskGraphValidationFailedStatus validation_failed = 2;
  }
}

message TaskGraphValidResult {}

message StartSessionRequest {
  string title = 1;
  TaskGraph task_graph = 2;
}

message StartSessionResponse {
  oneof result {
    SessionStartedResult started = 1;
    TaskGraphValidationFailedStatus validation_failed = 2;
  }
}

message SessionStartedResult {
  string session_id = 1;
}

message TaskGraph {
  repeated Task tasks = 1;
}

message Task {
  string id = 1;
  string label = 2;
  string description = 3;
  repeated string source_task_ids = 4;
  double x = 5;
  double y = 6;
}
