version: '3'

# noinspection YAMLSchemaValidation
.protoSources: &protoSources
  - '**/*.proto'

tasks:
  checkFormatting:
    desc: Check Protobuf formatting
    sources: *protoSources
    cmds:
      - buf format --diff --exit-code

  fixFormatting:
    desc: Fix Protobuf formatting
    sources: *protoSources
    cmds:
      - buf format --write

  lint:
    desc: Lint the Protobuf sources
    sources: *protoSources
    cmds:
      - buf lint
