version: '3'

tasks:
  install:
    desc: Install dependencies
    run: once
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json
    cmds:
      # Using `--immutable` ensures a clean install based on the lockfile
      - yarn install --immutable

  proto:
    desc: Generate code from protobuf definitions
    deps: [install]
    sources:
      - ../../../../proto/**/*.proto
    generates:
      - src/gen/**/*.ts
    cmds:
      - buf generate

  checkFormatting:
    desc: Check package formatting
    deps: [install, proto]
    cmds:
      - npx oxfmt --check "**/*.{ts,tsx,css}"

  fixFormatting:
    desc: Fix package formatting
    deps: [install]
    cmds:
      - npx oxfmt --write "**/*.{ts,tsx,css}"

  lint:
    desc: Lint the package
    deps: [install, proto]
    cmds:
      - npx oxlint
      - npx stylelint '**/*.css' --cache

  typecheck:
    desc: Type check the package
    deps: [install, proto]
    cmds:
      - npx tsc --noEmit

  runDev:
    desc: Start dev server
    deps: [install, proto]
    requires:
      vars:
        - CORE_SERVICE_URL
    env:
      VITE_CORE_SERVICE_URL: '{{.CORE_SERVICE_URL}}'
    cmds:
      - npx vite
    interactive: true
