version: '3'

tasks:
  install:
    desc: Install dependencies
    run: once
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json
    cmds:
      # Using `npm ci` ensures a clean install based on the lockfile
      - npm ci

  proto:
    desc: Generate code from protobuf definitions
    deps: [install]
    sources:
      - ../../../../proto/**/*.proto
    generates:
      - src/gen/**/*.ts
    cmds:
      - buf generate

  checkFormatting:
    desc: Check package formatting
    deps: [install, proto]
    cmds:
      - npx prettier --check .

  fixFormatting:
    desc: Fix package formatting
    deps: [install]
    cmds:
      - npx prettier --write .

  lint:
    desc: Lint the package
    deps: [install, proto]
    cmds:
      - npx eslint .

  typecheck:
    desc: Type check the package
    deps: [install, proto]
    cmds:
      - npx tsc -p tsconfig.json --noEmit

  buildProdDist:
    desc: Build the package
    deps: [install, proto]
    requires:
      vars:
        - CORE_SERVICE_URL
    env:
      VITE_CORE_SERVICE_URL: '{{.CORE_SERVICE_URL}}'
    cmds:
      - npx vite build --mode production

  runDev:
    desc: Start dev server
    deps: [install, proto]
    requires:
      vars:
        - CORE_SERVICE_URL
    env:
      VITE_CORE_SERVICE_URL: '{{.CORE_SERVICE_URL}}'
    cmds:
      - npx vite
    interactive: true
